variables:
  REGISTRY: "..../${SERVICE_NAME}"
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_TAG_TEST: latest-test
  DOCKER_TAG_PROD: latest

stages:
  - build
  - deploy


.build-template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"
      --cache=true
      --cache-run-layers
      --cache-copy-layers
      --log-timestamp=true
      --image-download-retry=2
  retry: 2
  
build-test:
  extends: .build-template
  only:
    - develop
  variables:
    TAG: ${DOCKER_TAG_TEST}

build-prod:
  extends: .build-template
  only:
    - master
  variables:
    TAG: ${DOCKER_TAG_PROD}


.deploy-template:
  stage: deploy
  image: docker:latest
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - ssh-keyscan $HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker compose -f docker-compose.yml pull
    - docker compose -f docker-compose.yml down --timeout=60 --remove-orphans
    - docker compose -f docker-compose.yml up --build --detach
    - docker image prune -f || true

deploy-test:
  extends: .deploy-template
  only:
    - develop
  variables:
    DOCKER_HOST: "ssh://$USER_TEST@$HOST_TEST"
    HOST: $HOST_TEST
    USER: $USER_TEST
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_TEST
    SPRING_PROFILES: test
    TAG: ${DOCKER_TAG_TEST}

deploy-prod:
  extends: .deploy-template
  only:
    - master
  variables:
    DOCKER_HOST: "ssh://$USER_PROD@$HOST_PROD"
    HOST: $HOST_PROD
    USER: $USER_PROD
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_PROD
    SPRING_PROFILES: prod
    TAG: ${DOCKER_TAG_PROD}
